// forge_cli/templates/react/src/frontend/App.jsx
import { useState, useEffect, useCallback } from 'react'
import { invoke } from '@forgedesk/api'
import './App.css'

function App() {
  const [todos, setTodos] = useState([])
  const [text, setText] = useState('')
  const [filter, setFilter] = useState('all')
  const [loading, setLoading] = useState(true)

  const loadTodos = useCallback(async () => {
    try {
      const data = await invoke('todo_list')
      setTodos(data)
    } catch (err) {
      console.error('Failed to load todos:', err)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { loadTodos() }, [loadTodos])

  const addTodo = async () => {
    if (!text.trim()) return
    try {
      await invoke('todo_add', { text: text.trim() })
      setText('')
      await loadTodos()
    } catch (err) {
      console.error('Failed to add todo:', err)
    }
  }

  const toggleTodo = async (id) => {
    try {
      await invoke('todo_toggle', { id })
      await loadTodos()
    } catch (err) {
      console.error('Failed to toggle todo:', err)
    }
  }

  const deleteTodo = async (id) => {
    try {
      await invoke('todo_delete', { id })
      await loadTodos()
    } catch (err) {
      console.error('Failed to delete todo:', err)
    }
  }

  const clearCompleted = async () => {
    try {
      await invoke('todo_clear_completed')
      await loadTodos()
    } catch (err) {
      console.error('Failed to clear completed:', err)
    }
  }

  const filtered = todos.filter(t => {
    if (filter === 'active') return !t.done
    if (filter === 'completed') return t.done
    return true
  })

  const left = todos.filter(t => !t.done).length

  return (
    <div className="app">
      <header className="app-header">
        <h1>{{PROJECT_NAME}}</h1>
        <p className="subtitle">What needs to be done?</p>
      </header>

      <main className="todo-container">
        <div className="input-wrapper">
          <input
            type="text"
            value={text}
            onChange={e => setText(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && addTodo()}
            placeholder="What needs to be done?"
            autoComplete="off"
          />
          <button onClick={addTodo} className="btn-primary">Add</button>
        </div>

        <div className="filters">
          {['all', 'active', 'completed'].map(f => (
            <button
              key={f}
              className={`filter ${filter === f ? 'active' : ''}`}
              onClick={() => setFilter(f)}
            >
              {f[0].toUpperCase() + f.slice(1)}
            </button>
          ))}
        </div>

        {loading ? (
          <div className="loading">Loading todos...</div>
        ) : (
          <ul className="todo-list">
            {filtered.map(todo => (
              <li key={todo.id} className={`todo-item ${todo.done ? 'completed' : ''}`}>
                <label className="todo-check">
                  <input
                    type="checkbox"
                    checked={todo.done}
                    onChange={() => toggleTodo(todo.id)}
                  />
                  <span className="checkmark"></span>
                </label>
                <span className="todo-text">{todo.text}</span>
                <button
                  className="btn-delete"
                  onClick={() => deleteTodo(todo.id)}
                  title="Delete"
                >
                  &times;
                </button>
              </li>
            ))}
          </ul>
        )}

        <div className="todo-footer">
          <span>{left} item{left !== 1 ? 's' : ''} left</span>
          <button className="btn-text" onClick={clearCompleted}>
            Clear completed
          </button>
        </div>
      </main>

      <footer className="app-footer">
        <p>Press <kbd>Enter</kbd> to add a todo</p>
        <p className="powered">Powered by <strong>Forge</strong> + React + Python</p>
      </footer>
    </div>
  )
}

export default App

// forge_cli/templates/svelte/src/frontend/App.svelte
<script>
  import { onMount } from 'svelte';
  import { invoke } from '@forgedesk/api';
  import './style.css';

  let todos = [];
  let text = '';
  let filter = 'all';
  let loading = true;
  const filters = ['all', 'active', 'completed'];

  $: filtered = filter === 'active'
    ? todos.filter(t => !t.done)
    : filter === 'completed'
    ? todos.filter(t => t.done)
    : todos;

  $: left = todos.filter(t => !t.done).length;

  async function loadTodos() {
    try {
      todos = await invoke('todo_list');
    } catch (err) {
      console.error('Failed to load todos:', err);
    } finally {
      loading = false;
    }
  }

  async function addTodo() {
    if (!text.trim()) return;
    try {
      await invoke('todo_add', { text: text.trim() });
      text = '';
      await loadTodos();
    } catch (err) {
      console.error('Failed to add todo:', err);
    }
  }

  async function toggleTodo(id) {
    try {
      await invoke('todo_toggle', { id });
      await loadTodos();
    } catch (err) {
      console.error('Failed to toggle todo:', err);
    }
  }

  async function deleteTodo(id) {
    try {
      await invoke('todo_delete', { id });
      await loadTodos();
    } catch (err) {
      console.error('Failed to delete todo:', err);
    }
  }

  async function clearCompleted() {
    try {
      await invoke('todo_clear_completed');
      await loadTodos();
    } catch (err) {
      console.error('Failed to clear completed:', err);
    }
  }

  onMount(loadTodos);
</script>

<div class="app">
  <header class="app-header">
    <h1>{{PROJECT_NAME}}</h1>
    <p class="subtitle">What needs to be done?</p>
  </header>

  <main class="todo-container">
    <div class="input-wrapper">
      <input
        type="text"
        bind:value={text}
        on:keydown={e => e.key === 'Enter' && addTodo()}
        placeholder="What needs to be done?"
        autocomplete="off"
      />
      <button on:click={addTodo} class="btn-primary">Add</button>
    </div>

    <div class="filters">
      {#each filters as f}
        <button
          class="filter {filter === f ? 'active' : ''}"
          on:click={() => filter = f}
        >
          {f[0].toUpperCase() + f.slice(1)}
        </button>
      {/each}
    </div>

    {#if loading}
      <div class="loading">Loading todos...</div>
    {:else}
      <ul class="todo-list">
        {#each filtered as todo (todo.id)}
          <li class="todo-item {todo.done ? 'completed' : ''}">
            <label class="todo-check">
              <input
                type="checkbox"
                checked={todo.done}
                on:change={() => toggleTodo(todo.id)}
              />
              <span class="checkmark"></span>
            </label>
            <span class="todo-text">{todo.text}</span>
            <button class="btn-delete" on:click={() => deleteTodo(todo.id)} title="Delete">
              &times;
            </button>
          </li>
        {/each}
      </ul>
    {/if}

    <div class="todo-footer">
      <span>{left} item{left !== 1 ? 's' : ''} left</span>
      <button class="btn-text" on:click={clearCompleted}>
        Clear completed
      </button>
    </div>
  </main>

  <footer class="app-footer">
    <p>Press <kbd>Enter</kbd> to add a todo</p>
    <p class="powered">Powered by <strong>Forge</strong> + Svelte + Python</p>
  </footer>
</div>
